config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'about' => 'static_pages#about' 
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :followers, :following
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<hr/>
<h2 class="text-center">
	| 
	<a href="mailto:karan.valecha92@gmail.com"><i class="fa fa-envelope-o text-danger"></i></a> |
	<a href="https://github.com/karan619"><i class="fa fa-github-square"></i></a> |
	<a href="https://facebook.com/karanvalecha619"><i class="fa fa-facebook-official"></i></a> |
	<a href="https://twitter.com/valechakaran619"><i class="fa fa-twitter-square text-primary"></i></a> |
	<a href="https://google.com/+karanvalecha619"><i class="fa fa-google-plus-square text-danger"></i></a> |
	<a href="https://in.linkedin.com/in/karanvalecha"><i class="fa fa-linkedin-square text-info"></i></a> |
</h2>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TweetPosts", root_path, id: "logo", class: 'navbar-brand btn-link navbar-btn'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Home", root_path, class: 'btn-link navbar-btn' %> </li>
         <li><%= link_to "Help", help_path, class: 'btn-link navbar-btn' %></li>
         <% if logged_in? %>
          <li><%= link_to "Users", users_path, class: 'btn-link navbar-btn' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle btn-link navbar-btn" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, class: 'btn-link navbar-btn' %></li>
        <% end %>
          </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>
</div>
<div class="container-fluid">
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/layouts/ex_header.html.erb
<header class="navbar  navbar-inverse">
  <div class="container-fluid">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TwiTTer", root_path, id: "logo", class: 'navbar-brand'%>
  </div>
      <nav>
        <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home", root_path, class: 'btn btn-link' %> </li>
         <li><%= link_to "Help", help_path, class: 'btn btn-link' %></li>
         <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        </ul>
      </nav>
  </div>
</header>